# Docker image for nightly deployment cronjob.

FROM gcr.io/gabrielwen-learning/test-worker:latest
MAINTAINER Gabriel Wen

# Never prompt the user for choices on installation/configuration of packages
ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=linux
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
